name: ".NET Core Library"
on:
  workflow_call:
    secrets:
      myget_nuget_apikey:
        required: true
      nuget_auth_token:
        required: true

jobs:
  
  build-and-push-alpha:
    if: startsWith(github.ref, 'refs/heads/feature')
    uses: ./.github/workflows/build-netcore-library.yml
    with:
      buildConfiguration: 'Debug'
      versionSuffix: alpha.${{ github.run_number }}
      nuget_username: ${{ github.actor }}
    secrets:
      myget_nuget_apikey: ${{ secrets.myget_nuget_apikey }}
      nuget_auth_token: ${{ secrets.nuget_auth_token }}

  build-and-push-beta:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/build-netcore-library.yml
    with:
      buildConfiguration: 'Debug'
      versionSuffix: alpha.${{ github.run_number }}
      nuget_username: ${{ github.actor }}
    secrets:
      myget_nuget_apikey: ${{ secrets.myget_nuget_apikey }}
      nuget_auth_token: ${{ secrets.nuget_auth_token }}

  build-and-push-rc:
    if: startsWith(github.ref, 'refs/heads/hotfix') || startsWith(github.ref, 'refs/heads/release')
    uses: ./.github/workflows/build-netcore-library.yml
    with:
      buildConfiguration: 'Release'
      versionSuffix: rc.${{ github.run_number }}
      nuget_username: ${{ github.actor }}
    secrets:
      myget_nuget_apikey: ${{ secrets.myget_nuget_apikey }}
      nuget_auth_token: ${{ secrets.nuget_auth_token }}

  build-and-push-stable:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build-netcore-library.yml
    with:
      buildConfiguration: 'Release'
      version: ${GITHUB_REF/refs\/tags\//}
      nuget_username: ${{ github.actor }}
    secrets:
      myget_nuget_apikey: ${{ secrets.myget_nuget_apikey }}
      nuget_auth_token: ${{ secrets.nuget_auth_token }}
