name: ".NET Core Library"
on:
  workflow_call:
    inputs:
      buildConfiguration:
        required: false
        type: string
        default: Debug
      versionSuffix:
        required: false
        type: string
        default: ''
      version:
        required: false
        type: string
        default: ''
    secrets:
      myget_nuget_apikey:
        required: true

env:
  MYGET_NUGET_APIKEY: ${{ secrets.myget_nuget_apikey }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Build and Pack
        if: inputs.versionSuffix != ''
        env:
          MYGET_NUGET_APIKEY: ${{ secrets.myget_nuget_apikey }}
        run: |
        project_name=$(basename *.sln .sln)
        dotnet pack --configuration ${{ inputs.buildConfiguration }} --version-suffix=${{ inputs.versionSuffix }} --output=package/${{ inputs.buildConfiguration }} $project_name/$project_name.csproj
        
      - name: Build and Pack (stable)
        if: inputs.version != ''
        env:
          MYGET_NUGET_APIKEY: ${{ secrets.myget_nuget_apikey }}
        run: |
        project_name=$(basename *.sln .sln)
        dotnet pack --configuration ${{ inputs.buildConfiguration }} --output=package/${{ inputs.buildConfiguration }} $project_name/$project_name.csproj /p:Version=${{ inputs.version }}
      
      - name: Publish
        run: dotnet nuget push package/${{ inputs.buildConfiguration }}/*.nupkg
