name: "Build & Deploy Glue Lambda Service"

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true
      aws_role_to_assume:
        required: false
      hb_github_ssh_key:
        required: true
      hb_github_packages_read_only_token:
        required: true



jobs:
  build:
    name: "Build & Deploy Service"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: './checkout'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout Glue
        uses: actions/checkout@v3
        with:
          repository: holdbar-com/glue
          ref: main
          path: './glue'
          ssh-key: ${{ secrets.hb_github_ssh_key }}

      - name: Checkout node-aws-env
        uses: actions/checkout@v3
        with:
          repository: holdbar-com/node-aws-env
          ref: v1.0.4
          path: './node-aws-env'
          ssh-key: ${{ secrets.hb_github_ssh_key }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.hb_github_ssh_key }}

      - name: Install & Setup node-aws-env
        run: |
          cd ./node-aws-env
          npm install -g typescript eslint
          npm install
          tsc

      - name: Configure AWS credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          role-session-name: Github-Actions-Glue-Session
          role-duration-seconds: 3600

      - name: Build
        run: |
          cd ./checkout
          echo -e "@holdbar-com:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.hb_github_packages_read_only_token }}" > .npmrc
          npm install
          tsc 
          eslint
          node ./node_modules/@riddance/env/bin/prepare.js
          node ./node_modules/@riddance/env/bin/install.js ${{ github.workspace }}/checkout

      - name: Test
        run: |
          cd ./checkout
          npm test

      - name: Deploy
        run: |
          cd ./checkout
          node ../node-aws-env/bin/deploy.js --env ${{ inputs.stage }} --glue-file ../glue/${{ inputs.stage }}/glue.json
